# Generated by Django 2.2.4 on 2019-08-31 10:14

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desription', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='movies')),
                ('category', models.CharField(choices=[('A', 'ACTION'), ('C', 'COMEDY'), ('R', 'ROMANCE'), ('D', 'DRAMA')], max_length=1)),
                ('language', models.CharField(choices=[('EN', 'ENGLISH'), ('HI', 'HINDI')], max_length=2)),
                ('status', models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('MW', 'MOST WATCHED'), ('TR', 'TOP RATED')], max_length=2)),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
