# Generated by Django 2.2.4 on 2019-09-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190901_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DL', 'DOWNLOAD LINK'), ('WL', 'WATCH LINK')], max_length=2)),
                ('link', models.URLField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_watch_list', to='movie.Movie')),
            ],
        ),
        migrations.DeleteModel(
            name='MovieLinks',
        ),
    ]
