# Generated by Django 2.2.4 on 2019-09-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190901_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action', 'ACTION'), ('Comedy', 'COMEDY'), ('Romance', 'ROMANCE'), ('Drama', 'DRAMA')], max_length=10),
        ),
    ]
