# Generated by Django 2.2.4 on 2019-09-01 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20190901_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 2, 0, 35, 55, 823778)),
        ),
    ]
