# Generated by Django 2.2.4 on 2019-09-03 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 3, 22, 37, 46, 951515)),
        ),
    ]
