# Generated by Django 2.2.4 on 2019-09-03 18:58

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20190903_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 9, 4, 0, 28, 41, 262556)),
        ),
    ]
